using IDEASLabUT.MSBandWearable.Core.Json;
using Newtonsoft.Json;
using System;

namespace IDEASLabUT.MSBandWearable.Core.Model
{
    /// <summary>
    /// An abstract class providing basis for all MS Band 2 sensor events common details
    /// </summary>
    public abstract class BaseEvent
    {
        /// <summary>
        /// A time which this event is acquired or accumulated or received
        /// </summary>
        [JsonConverter(typeof(ZonedDateTimeOptionalNanoConverter))]
        [JsonProperty("acquiredTime")]
        public DateTime AcquiredTime { get; set; }

        /// <summary>
        /// A time which this event is generated by sensor
        /// </summary>
        [JsonConverter(typeof(ZonedDateTimeOptionalNanoConverter))]
        [JsonProperty("actualTime")]
        public DateTime ActualTime { get; set; }

        /// <summary>
        /// A type of wearable band which this events belongs to
        /// </summary>
        [JsonConverter(typeof(BandTypeConverter))]
        [JsonProperty("bandType")]
        public BandType BandType { get; private set; } = BandType.MSBand;

        /// <summary>
        /// An iOS SwiftUI view which subject is using in iPAD wearing the band from which event is generated 
        /// </summary>
        [JsonProperty("fromView")]
        public string FromView { get; set; }

        /// <summary>
        /// A unique identifier of subject in the running experiment wearing the band which generates this event
        /// </summary>
        [JsonProperty("subjectId")]
        public string SubjectId { get; set; }

        /// <summary>
        /// Returns a serialized json representation of <see cref="BaseEvent"/>
        /// </summary>
        /// <returns>A serialized json string</returns>
        public override string ToString()
        {
            return JsonConvert.SerializeObject(this);
        }
    }
}
